# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c4862b73a02d793ba3a28248e00ce36d82d4b0d27a6b2fd1b8da02a943cd0ea9d5a40c7160b0a1d7ad375733ebd1e33dc6111da3022351146c563b2af8bebe9

test:
  secret_key_base: d057121d5c26a02486b161cd1b5f5722bf76217b7eb80ff46d9fcbb2350140e11b4662f1c79e7eaed7ac2268345d592302cd4471e86b9eb76fb73b53a97ec818

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 973accee6f9ba889f1f1d58242b80e90a82e59e25d78cef83a5ddcb482e59962b5844cfa2975e18dc05ff5961f6d949f19b509e07f5b5f9bd7409b1f08a4fc6a

